{% set name = "gstlal" %}
{% set version = "1.13.0" %}

# requirements (should match MIN_<> in configure.ac)
{% set dqsegdb2_version = "1.0.1" %}
{% set gwdatafind_version = "1.1.0" %}
{% set lal_version = "7.2.4" %}
{% set lalmetaio_version = "3.0.2" %}
{% set lalsimulation_version = "4.0.2" %}
{% set lalburst_version = "1.7.0" %}
{% set lalinspiral_version = "3.0.2" %}
{% set ligo_segments_version = "1.2.0" %}
{% set pluggy_version = "0.6.0" %}
{% set python_condor_version = "8.9.0" %}
{% set ligo_lw_version = "1.8.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://software.igwn.org/sources/source/{{ name }}-{{ version }}.tar.gz
  sha256: 669617b05c123c3b95b1ae7538954e01b0ca2ca41cf3dea87ab1398eab1ca6a1
  patches:
    # update use of imp module in py-compile (autoconf)
    - py-compile-imp.patch
    # fix incompatible pointer error for Python 3.12
    - pyobject_head_init.patch
    # backport https://git.ligo.org/lscsoft/gstlal/-/merge_requests/610
    - bottle-imp.patch

build:
  error_overlinking: true
  ignore_run_exports:
    # these are needed for the build, and at runtime,
    # but aren't actually directly linked against
    - gobject-introspection
    - gst-python
  number: 4
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - pkg-config >=0.18.0
    - make
  host:
    - fftw
    - glib
    - gobject-introspection >=1.30.0
    - gsl
    - gstreamer
    - gstreamer-orc
    - gst-plugins-base  {{ gstreamer }}
    - gst-python
    - libglib
    - liblal >={{ lal_version }}
    - liblalmetaio >={{ lalmetaio_version }}
    - liblalburst >={{ lalburst_version }}
    - liblalinspiral >={{ lalinspiral_version }}
    - liblalsimulation >={{ lalsimulation_version }}
    - numpy
    - pygobject >=3.22,<=3.46
    - python
    - python-lal
    - python-ligo-lw >={{ ligo_lw_version }}
    - zlib
  run:
    - dqsegdb2 >={{ dqsegdb2_version }}
    - fftw
    - gobject-introspection >=1.30.0
    - gsl
    - gstreamer-orc
    - gst-plugins-good  {{ gstreamer }}
    - gst-python
    - gwdatafind >={{ gwdatafind_version }}
    - jinja2
    - libglib
    - liblal >={{ lal_version }}
    - liblalmetaio >={{ lalmetaio_version }}
    - liblalburst >={{ lalburst_version }}
    - liblalinspiral >={{ lalinspiral_version }}
    - liblalsimulation >={{ lalsimulation_version }}
    - ligo-segments >={{ ligo_segments_version }}
    - matplotlib-base
    - numpy
    - pandas
    - pluggy >={{ pluggy_version }}
    - pyfftw
    - pygobject >=3.22,<=3.46
    - python
    - python-avahi
    - python-htcondor >={{ python_condor_version }}
    - python-lal >={{ lal_version }}
    - python-lalsimulation >={{ lalsimulation_version }}
    - python-ligo-lw >={{ ligo_lw_version }}
    - scipy
    - setuptools
  run_constrained:
    # https://github.com/conda-forge/backports-feedstock/issues/6
    - setuptools <71.0.0  # [py<39]

test:
  requires:
    - pkg-config
  commands:
    # set variables
    - export TMPDIR=$(python -c "import tempfile; print(tempfile.gettempdir())")
    - export GSTLAL_FIR_WHITEN=0
    # check executables
    - gstlal_asd_txt_from_psd_xml --help
    - gstlal_dagfile_rerun_relatives --help
    - gstlal_fake_frames --help
    - gstlal_fake_frames_workflow --help
    - gstlal_grid_profile --help
    - gstlal_launch --help
    - gstlal_ligo_data_find_check --help
    - gstlal_play --help
    - gstlal_plot_psd --help
    - gstlal_psd_polyfit --help
    - gstlal_psd_workflow --help
    - gstlal_psd_xml_from_asd_txt --help
    - gstlal_query_dqsegdb_segments --help
    - gstlal_query_dqsegdb_veto_segments --help
    - gstlal_query_gwosc_segments --help
    - gstlal_query_gwosc_veto_segments --help
    - gstlal_reference_psd --help
    - gstlal_spectrum_movie --help
    # check pkg-config
    - pkg-config --print-errors --exact-version {{ version }} gstlal  # [unix]

about:
  home: https://lscsoft.docs.ligo.org/gstlal/
  dev_url: https://git.ligo.org/lscsoft/gstlal/
  doc_url: https://lscsoft.docs.ligo.org/gstlal/
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: GStreamer for GW data analysis
  description: |
    This package provides a variety of gstreamer elements for
    gravitational-wave data analysis and some libraries to help write
    such elements.  The code here sits on top of several other libraries,
    notably the LIGO Algorithm Library (LAL), FFTW, the GNU Scientific
    Library (GSL), and, of course, GStreamer.
    This package contains the plugins and shared libraries required to run
    gstlal-based applications.

extra:
  recipe-maintainers:
    - aepace
    - duncanmmacleod
    - myNameIsPatrick
