{% set name = "gstlal" %}
{% set version = "1.5.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "http://software.ligo.org/lscsoft/source/{{ name }}-{{ version }}.tar.gz"
  sha256: 92926bfc692adea418b8aaaf87663eae10970c78bf4dd0e2fd36c1b68c43392f
  patches:
    - out-of-tree.patch
    - no-pygtk.patch
    - python-lib-loc.patch

build:
  error_overdepending: true
  error_overlinking: true
  number: 2
  skip: true  # [win or py>=30]

requirements:
  build:
    - {{ compiler('c') }}
    - pkg-config
    - make
  host:
    - fftw
    - gsl
    - gstreamer
    - gst-plugins-base
    - gst-plugins-good
    - gst-python
    - lal >=6.19.0
    - lalmetaio >=1.4.0
    - lalburst >=1.5.0
    - lalinspiral >=1.8.0
    - lalsimulation >=1.8.0
    - numpy
    - pygobject >=3.22
    - python
    - python-lal
    - python-ligo-lw >=1.5.3
    - zlib
  run:
    - fftw
    - glib
    - gsl
    - gstreamer
    - gst-plugins-base
    - gst-plugins-good
    - gst-python
    - lal >=6.19.0
    - lalmetaio >=1.4.0
    - lalburst >=1.5.0
    - lalinspiral >=1.8.0
    - lalsimulation >=1.8.0
    - ligo-segments >=1.2.0
    - lscsoft-glue >=2.0.0
    - matplotlib-base
    - {{ pin_compatible('numpy') }}
    - pyfftw
    - pygobject >=3.14
    - python 2.7
    - python
    - python-avahi
    - python-lal >=6.19.0
    - python-lalsimulation
    - python-ligo-lw >=1.5.3

test:
  imports:
    - gstlal
    - gstlal.bottle
    - gstlal.coherent_null
    - gstlal.dagfile
    - gstlal.datasource
    - gstlal.elements
    - gstlal.httpinterface
    - gstlal.matplotlibhelper
    - gstlal.misc
    #- gstlal.multirate_datasource - requires GSTLAL_FIR_WHITEN variable, see below
    - gstlal.pipeio
    - gstlal.pipeline
    - gstlal.pipeparts
    - gstlal.plotpsd
    - gstlal.plotutil
    - gstlal.reference_psd
    - gstlal.servicediscovery
    - gstlal.simplehandler
    - gstlal.simulation
    - gstlal.stats
  requires:
    - pkg-config
  commands:
    # set variables
    - export TMPDIR=$(python -c "import tempfile; print(tempfile.gettempdir())")
    - export GSTLAL_FIR_WHITEN=0
    # check last import (which requires GSTLAL_FIR_WHITEN)
    - ${PYTHON} -c "import gstlal.multirate_datasource"
    # check executables
    - gstlal_asd_txt_from_psd_xml --help
    - gstlal_fake_frames --help
    - gstlal_launch --help
    - gstlal_ligo_data_find_check --help
    - gstlal_play --help
    - gstlal_plot_psd --help
    - gstlal_plot_psd_horizon --help
    - gstlal_psd_polyfit --help
    - gstlal_psd_xml_from_asd_txt --help
    - gstlal_reference_psd --help
    - gstlal_spectrum_movie --help
    # check pkg-config
    - pkg-config --print-errors --modversion gstlal  # [unix]

about:
  home: "https://lscsoft.docs.ligo.org/gstlal/"
  dev_url: "https://git.ligo.org/lscsoft/gstlal/"
  doc_url: "https://lscsoft.docs.ligo.org/gstlal/"
  license: "GPL-2.0-or-later"
  license_family: "GPL"
  license_file: "COPYING"
  summary: "GStreamer for GW data analysis"
  description: |
    This package provides a variety of gstreamer elements for
    gravitational-wave data analysis and some libraries to help write
    such elements.  The code here sits on top of several other libraries,
    notably the LIGO Algorithm Library (LAL), FFTW, the GNU Scientific
    Library (GSL), and, of course, GStreamer.
    This package contains the plugins and shared libraries required to run
    gstlal-based applications.

extra:
  recipe-maintainers:
    - duncanmmacleod
    - myNameIsPatrick
