{% set name = "gstlal" %}
{% set version = "1.8.0" %}

# requirements
{% set lal_version = "7.1.0" %}
{% set lalmetaio_version = "2.0.0" %}
{% set lalsimulation_version = "2.5.0" %}
{% set lalburst_version = "1.5.0" %}
{% set lalinspiral_version = "2.0.0" %}
{% set ligo_segments_version = "1.2.0" %}
{% set lscsoft_glue_version = "2.0.0" %}
{% set python_ligo_lw_version = "1.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://software.igwn.org/sources/source/{{ name }}-{{ version }}.tar.gz
  sha256: ccb7b5cf8ce5df79cc84ded4d7c6e5e030afcfb91f0b2c92a247193f35d5d21a
  patches:
    - no-pygtk.patch

build:
  error_overdepending: true
  error_overlinking: true
  ignore_run_exports:
    - gobject-introspection
    - gst-python
  number: 0
  # SyntaxErrors on python>=3.7 use of 'async' reserved keyword
  skip: true  # [win or py>36]

requirements:
  build:
    - {{ compiler('c') }}
    - pkg-config >=0.18.0
    - make
  host:
    - fftw
    - gobject-introspection >=1.30.0
    - gsl
    - gstreamer
    - gst-plugins-base
    - gst-python
    - libglib
    - liblal >={{ lal_version }}
    - liblalmetaio >={{ lalmetaio_version }}
    - liblalburst >={{ lalburst_version }}
    - liblalinspiral >={{ lalinspiral_version }}
    - liblalsimulation >={{ lalsimulation_version }}
    - numpy
    - pygobject >=3.22
    - python
    - python-lal
    - python-ligo-lw >={{ python_ligo_lw_version }}
    - zlib
  run:
    - fftw
    - gobject-introspection >=1.30.0
    - gsl
    - gstreamer
    - gst-plugins-base
    - gst-plugins-good
    - gst-python
    - lal >={{ lal_version }}
    - lalmetaio >={{ lalmetaio_version }}
    - lalburst >={{ lalburst_version }}
    - lalinspiral >={{ lalinspiral_version }}
    - lalsimulation >={{ lalsimulation_version }}
    - libglib
    - ligo-segments >={{ ligo_segments_version }}
    - lscsoft-glue >={{ lscsoft_glue_version }}
    - matplotlib-base
    - {{ pin_compatible('numpy') }}
    - pyfftw
    - pygobject >=3.14
    - python 2.7
    - python
    - python-avahi
    - python-lal >={{ lal_version }}
    - python-lalsimulation
    - python-ligo-lw >={{ python_ligo_lw_version }}
    - scipy

test:
  imports:
    - gstlal
    - gstlal.bottle
    - gstlal.coherent_null
    - gstlal.dagfile
    - gstlal.datasource
    - gstlal.elements
    - gstlal.httpinterface
    - gstlal.matplotlibhelper
    - gstlal.misc
    #- gstlal.multirate_datasource - requires GSTLAL_FIR_WHITEN variable, see below
    - gstlal.pipeio
    - gstlal.pipeline
    - gstlal.pipeparts
    - gstlal.plotpsd
    - gstlal.plotutil
    - gstlal.reference_psd
    - gstlal.servicediscovery
    - gstlal.simplehandler
    - gstlal.simulation
    - gstlal.stats
  requires:
    - pkg-config
  commands:
    # set variables
    - export TMPDIR=$(python -c "import tempfile; print(tempfile.gettempdir())")
    - export GSTLAL_FIR_WHITEN=0
    # check last import (which requires GSTLAL_FIR_WHITEN)
    - ${PYTHON} -c "import gstlal.multirate_datasource"
    # check executables
    - gstlal_asd_txt_from_psd_xml --help
    - gstlal_fake_frames --help
    - gstlal_launch --help
    - gstlal_ligo_data_find_check --help
    - gstlal_play --help
    - gstlal_plot_psd --help
    - gstlal_plot_psd_horizon --help
    - gstlal_psd_polyfit --help
    - gstlal_psd_xml_from_asd_txt --help
    - gstlal_reference_psd --help
    - gstlal_spectrum_movie --help
    # check pkg-config
    - pkg-config --print-errors --modversion gstlal  # [unix]

about:
  home: "https://lscsoft.docs.ligo.org/gstlal/"
  dev_url: "https://git.ligo.org/lscsoft/gstlal/"
  doc_url: "https://lscsoft.docs.ligo.org/gstlal/"
  license: "GPL-2.0-or-later"
  license_family: "GPL"
  license_file: "COPYING"
  summary: "GStreamer for GW data analysis"
  description: |
    This package provides a variety of gstreamer elements for
    gravitational-wave data analysis and some libraries to help write
    such elements.  The code here sits on top of several other libraries,
    notably the LIGO Algorithm Library (LAL), FFTW, the GNU Scientific
    Library (GSL), and, of course, GStreamer.
    This package contains the plugins and shared libraries required to run
    gstlal-based applications.

extra:
  recipe-maintainers:
    - duncanmmacleod
    - myNameIsPatrick
