# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

language: generic

os: osx
osx_image: xcode9.4


env:
  matrix:
    - CONFIG=osx_python2.7
    - CONFIG=osx_python3.6
    - CONFIG=osx_python3.7

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "VeWc25IooocuTlg06shW7iq7fi9haifqYi05axt03GoCAzjsl08m/G1FP2YW815R0OPV7KeM+FRTVFYOTrK/EG7xw0MhS+d6RL61NDp03u/YtBRLvmhd8zmYwUcTH38hLbClFdFW3IZlOowtdRz0ROHC+t0KcHJcpYOh7hQhLJX8/MGWocX5isYf38bLQtnrCigN7A0+iNoy1YyrvxMzMkw+O9rU4BlAik8cX2K/YfyUDyigfM7iLSeJESNBQpZDhWANdGGo9bvsj6RD0hn5Di6ZNGyx6TGGcuHCU3h/HiL8bSV4axwrp8qC9pIZXHPZ9SMxkkBye8C8Bri2PMZY0Klj4irYXxGkvRhDjzd2J7baht4RQmhCgEYUdWbxDI/iHkDMWHsETFO3enWiq7MoAXdqXn2pFy1b/mwCauqOB+E8pLnOBjGNon+AOiZylsOdt9X/HP35OzXyZ/EQ4LIdSAfWyxsoYP2whKzuh2jtrbv0t3FqeO+yNqGLZQQ8+17vpCTFlMK1lesZJYL60+fWqhKVc5UOF2evfsrAbzAzNhji87cBs1qk43+aPpcOnoZNzPp09jSHSfU0CauZYuTwwmiyeTdPtq8SxyivkdFjkkQ8M+VUmqMoRp1G1abZnTbNVq2ywLWVIqEEmJX7VJ1UUVKIL/Vh3w7ICDIqa9TE/D8="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install -n root -c conda-forge --quiet --yes conda-forge-ci-setup=2 conda-build
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  -  conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml