travis:
  secure:
    BINSTAR_TOKEN: VeWc25IooocuTlg06shW7iq7fi9haifqYi05axt03GoCAzjsl08m/G1FP2YW815R0OPV7KeM+FRTVFYOTrK/EG7xw0MhS+d6RL61NDp03u/YtBRLvmhd8zmYwUcTH38hLbClFdFW3IZlOowtdRz0ROHC+t0KcHJcpYOh7hQhLJX8/MGWocX5isYf38bLQtnrCigN7A0+iNoy1YyrvxMzMkw+O9rU4BlAik8cX2K/YfyUDyigfM7iLSeJESNBQpZDhWANdGGo9bvsj6RD0hn5Di6ZNGyx6TGGcuHCU3h/HiL8bSV4axwrp8qC9pIZXHPZ9SMxkkBye8C8Bri2PMZY0Klj4irYXxGkvRhDjzd2J7baht4RQmhCgEYUdWbxDI/iHkDMWHsETFO3enWiq7MoAXdqXn2pFy1b/mwCauqOB+E8pLnOBjGNon+AOiZylsOdt9X/HP35OzXyZ/EQ4LIdSAfWyxsoYP2whKzuh2jtrbv0t3FqeO+yNqGLZQQ8+17vpCTFlMK1lesZJYL60+fWqhKVc5UOF2evfsrAbzAzNhji87cBs1qk43+aPpcOnoZNzPp09jSHSfU0CauZYuTwwmiyeTdPtq8SxyivkdFjkkQ8M+VUmqMoRp1G1abZnTbNVq2ywLWVIqEEmJX7VJ1UUVKIL/Vh3w7ICDIqa9TE/D8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
